# -*- coding: utf-8 -*-

from . import models
from . import checkout
from . import customclass
from . import statement
from . import res_partner
from . import unit_conversion
from . import machineprice
from . import maketype
from . import productpricetable
from . import productpricecalculator
from . import customproductwizard
from . import product_template
from . import saleorder
from . import product_att_val
from . import make_out
from . import make_in
from . import make_om
from . import installproduct
from . import stock
from . import barcode
from . import getuser
from . import deliveryorder
from . import account_report
from . import billinvoice
from . import upload_ftp
from . import store
from . import product_attribute_del
from . import checkoutreport
from . import lotmpr
from . import delivery_carrier 
from . import chattemplate 
from . import worker_qrcode 
from . import crm 
from . import website_sale 
from . import order_preview 
#from . import purchase_order
from . import ir_ui_menu
from . import linebot
from . import pettycash
from . import calendar
from . import performance
from . import interoperate