[options]
addons_path = /home/bryant/odooE/odoo/addons,/home/bryant/odooE/odoo/custom-addons
data_dir = /home/bryant/odoo-git/odoo-data
db_host = localhost
admin_passwd = 123123
proxy_mode = True
tax_id_number = 12345678 
hash_key = TESTONLY 
hash_iv = TESTONLY 
limit_time_real = 7200
limit_time_cpu = 7200
limit_memory_soft = 21474836480
limit_memory_hard = 26843545600
web.base.url = https://shop.coinimaging.com.tw