[options]
addons_path = /home/odoo/odoo16/odoo16E/src/odooE/odoo/addons,/home/odoo/odoo16/odoo16E/src/odooE/odoo/custom-addons
data_dir = /home/odoo/odoo16/odoo16E/data
db_host = 127.0.0.1
db_port = 5433
db_user = odoo
db_password = odoo
db_name = coinimaging
dbfilter = ^coinimaging$
list_db = False
admin_passwd = 123123
proxy_mode = False
workers = 0
max_cron_threads = 0
http_port = 8070
gevent_port = 8072
tax_id_number = 12345678
hash_key = TESTONLY
hash_iv = TESTONLY
limit_time_real = 7200
limit_time_cpu = 7200
limit_memory_soft = 21474836480
limit_memory_hard = 26843545600
without_demo = True
logfile = /home/odoo/odoo16/odoo16E/logs/odoo.log
web.base.url = http://127.0.0.1:8070
